# Parsing and manipulating expressions

```{r}
library(purrr)
library(rlang)
library(magrittr)
```

## Quoting and evaluating

```{r}
quote(2 * x + y)
```

```{r}
expr <- quote(2 * x + y)
class(expr)
```

```{r}
expr[[1]]
expr[[2]]
expr[[3]]
```


```{r}
expr[[2]][[1]]
expr[[2]][[2]]
expr[[2]][[3]]
```

```{r}
f <- function(expr) expr[[1]]
f(quote(2 * x + y))
```

```{r, error=TRUE}
f(2 * x + y)
```

```{r}
x <- 2
y <- 3
f(2 * x + y)
```

```{r}
f <- function(expr) {
  expr <- quote(expr)
  expr[[1]]
}
f(2 * x + y)
```

```{r}
f <- function(expr) {
  expr <- substitute(expr)
  expr[[1]]
}
f(2 * x + y)
```

```{r}
f <- function(expr) {
  expr <- substitute(expr + expr)
  expr
}
f(2 * x + y)
```

```{r}
f <- function(expr) {
  expr + expr
}
g <- function(expr) {
  x <- substitute(expr + expr)
  eval(x)
}
```

```{r}
x <- 2; y <- 3
f(2 * x + y)
```

```{r}
g(2 * x + y)
```

```{r}
g <- function(expr) {
  x <- substitute(expr + expr)
  eval(x, parent.frame())
}
g(2 * x + y)
```

## Exploring expressions

```{r}
print_expression <- function(expr, indent = "") {
  if (is.atomic(expr)) {
    if (inherits(expr, "srcref")) {
      expr <- paste0("srcref = ", expr)
    }
    cat(indent, " - ", expr, "\\n")
    
  } else if (is.name(expr)) {
    if (expr == "") {
      expr <- "MISSING"
    }
    cat(indent, " - ", expr, "\\n")
    
  } else if (is.primitive(expr)) {
    cat(indent, " - ", expr, "\\n")
    
  } else if (is.pairlist(expr)) {
    cat(indent, " - ", "[\\n")
    new_indent <- paste0(indent, "       ")
    vars <- names(expr)
    for (i in seq_along(expr)) {
      cat(indent, "    ", vars[i], " ->\\n")
      print_expression((expr[[i]]), new_indent)
    }
    cat(indent, "    ]\\n")
    
  } else {
    print_expression((expr[[1]]), indent)
    new_indent <- paste0("  ", indent)
    for (i in 2:length(expr)) {
      print_expression(expr[[i]], new_indent)
    }
  }
}
```

```{r}
print_expression(quote(2 * x + y))
```

```{r}
print_expression(quote(function(x) x))
```

```{r}
print_expression(quote(function(x = 2 * 2 + 4) x))
print_expression(quote(function(x, y = 2 * x) x + y))
```

```{r}
expr <- quote((function(x) x)(2))
print_expression(expr)
expr[[1]]
expr[[2]]
```

```{r}
cons <- function(car, cdr) list(car = car, cdr = cdr)
collect_symbols_rec <- function(expr, lst, bound) {
  if (is.symbol(expr) && expr != "") {
    if (as.character(expr) %in% bound) lst
    else cons(as.character(expr), lst)
    
  } else if (is.pairlist(expr)) {
    for (i in seq_along(expr)) {
      lst <- collect_symbols_rec(expr[[i]], lst, bound)
    }
    lst
    
  } else if (is.call(expr)) {
    if (expr[[1]] == as.symbol("function"))
      bound <- c(names(expr[[2]]), bound)
    
    for (i in 1:length(expr)) {
      lst <- collect_symbols_rec(expr[[i]], lst, bound)
    }
    lst
    
  } else {
    lst
  }
}
```

```{r}
lst_length <- function(lst) {
  len <- 0
  while (!is.null(lst)) {
    lst <- lst$cdr
    len <- len + 1
  }
  len
}
lst_to_list <- function(lst) {
  v <- vector(mode = "list", length = lst_length(lst))
  index <- 1
  while (!is.null(lst)) {
    v[[index]] <- lst$car
    lst <- lst$cdr
    index <- index + 1
  }
  v
}
```

```{r}
collect_symbols <- function(expr) {
  expr <- substitute(expr)
  bound <- c()
  lst <- collect_symbols_rec(expr, NULL, bound)
  lst %>% lst_to_list() %>% unique() %>% 
          purrr::discard(exists, parent.frame()) %>%
          unlist()
}
```


```{r}
rm(x) ; rm(y)
collect_symbols(2 * x + y + z)
```

```{r}
z <- 3
collect_symbols(2 * x + y + z)
```

```{r}
collect_symbols(function(x) 2 * x + y + z)
collect_symbols(function(x) function(y) f(2 * x + y))
```

```{r}
collect_symbols(function(x, y = 2 * w) 2 * x + y)
```

```{r}
f <- function(expr) collect_symbols(expr)
```

```{r}
f(2 + y * w)
```

```{r}
collect_symbols_ <- function(expr, env) {
  bound <- c()
  lst <- collect_symbols_rec(expr, NULL, bound)
  lst %>% lst_to_list() %>% unique() %>% 
    purrr::discard(exists, env) %>%
    unlist()
}
collect_symbols <- function(expr) {
  collect_symbols_(substitute(expr), parent.frame())
}
```

## Manipulating expressions

```{r}
f <- quote(function(x) 2 * x)
f
```

```{r}
f[[2]]
```

```{r}
f[[2]][[1]] <- quote(2 * y)
f
```

```{r}
names(f[[2]]) <- c("a")
f[[3]] <- quote(2 * a)
f
```

```{r}
expr <- quote(2 * x + y)
expr
expr[[1]] <- as.symbol("/")
expr
expr[[2]][[1]] <- as.symbol("+")
expr
```

```{r}
call("+", quote(2 * x), quote(y))
call("+", call("*", 2, quote(x)), quote(y))
```

```{r}
call("f", a = quote(2 * x), b = quote(y))
```

```{r}
z <- 2
call("+", 2 * z, quote(y))
```
```{r}
library(rlang)
lang("+", quote(2 * x), quote(y))
new_language(as.symbol("+"), pairlist(quote(2 * x), quote(y)))
```


```{r}
make_args_list <- function(args) {
  res <- replicate(length(args), substitute())
  names(res) <- args
  as.pairlist(res)
}
```

```{r}
f <- call("function", 
          make_args_list(c("x", "y")), 
          quote(2 * x + y))
f
```

```{r}
f(2, 3)
```

```{r}
f <- eval(f)
f
f(2, 3)
```

```{r}
f <- new_function(make_args_list(c("x", "y")), 
                  quote(2 * x + y))
f
f(2, 3)
```

```{r}
expr_to_function <- function(expr) {
  expr <- substitute(expr)
  unbound <- collect_symbols_(expr, caller_env())
  new_function(make_args_list(unbound), expr, caller_env())
}
```


```{r}
f <- expr_to_function(2 * x + y)
f
f(x = 2, y = 3)
g <- expr_to_function(function(x) 2 * x + y)
g
g(y = 3)(x = 2)
```

