# Environments and expressions {#sec:env_and_expr}

```{r}
library(rlang)
```


## Scopes and environments

```{r}
x <- 1
f <- function(y) {
  z <- 3
  function() x + y + z
}
g <- f(2)
h <- f(3)
g()
h()
```


```{r}
environment(f)
environment(g)
environment(h)
```


## Default parameters, lazy evaluation, and promises

```{r}
f <- function(x, y) x
f(2, stop("error!"))
```

```{r}
f <- function(y, z = 2 * y) y + z
```

```{r}
f(2, 1)
```

```{r}
f(2)
```

```{r}
y <- 2
f(2 * y)
```


```{r}
g <- function(x) f(2 * x)
g(2 * y)
```

```{r}
h <- function(x, y = 2 * w) {
  w <- 2
  x + y
}
h(1)
```

```{r, error=TRUE}
h <- function(x, y = 2 * w) {
  res <- x + y
  w <- 2
  res
}
h(1)
```

```{r}
h <- function(x, y = 2 * w) {
  w <- 1
  res <- x + y
  w <- 2
  res
}
h(1)
```

```{r}
make_adder <- function(n) function(m) n + m
```

```{r}
add_1 <- make_adder(1)
add_2 <- make_adder(2)
add_1(1)
add_2(1)
```

```{r}
adders <- vector("list", 3)
for (i in 1:3) adders[[i]] <- make_adder(i)
```

```{r}
adders[[1]](1)
```

```{r}
i <- 1
adders[[1]](1)
```

```{r}
adders[[2]](1)
```

```{r}
make_adder <- function(n) {
  force(n)
  function(m) n + m
}
for (i in 1:3) adders[[i]] <- make_adder(i)
for (i in 1:3) print(adders[[i]](0))
```


## Quotes and non-standard evaluation

```{r}
ex1 <- quote(2 * x + y)
ex1
f <- function(ex) substitute(ex)
ex2 <- f(2 * x + y)
ex2
```

```{r}
g <- rlang::new_function(alist(x=, y=), body = ex1)
g
g(1,3)
```

```{r}
x <- 1
y <- 3
eval(ex1)
```

```{r}
h <- function(x, y) eval(ex1)
h
h(1,3)
```

```{r}
h <- function(x, y) eval(ex1, rlang::caller_env())
x <- y <- 1
h(4,4)
```

```{r}
f <- function(x) rlang::new_function(alist(y=), ex1)
f(2)
f(2)(2)
```

```{r}
g <- function(x) {
  rlang::new_function(alist(y=), ex1, rlang::caller_env())
}
g(2)
g(2)(2)
```


```{r}
eval(ex1, list(x = 4, y = 8))
df <- data.frame(x = 1:4, y = 1:4)
eval(ex1, df)
```

```{r}
f <- function(expr, data, y) eval(expr, data)
g <- function(expr, data, y) eval(expr, data, rlang::caller_env())
```

```{r}
df <- data.frame(x = 1:4)
y <- 1:4
f(quote(x + y), df, y = 5:8) == 1:4 + 5:8
g(quote(x + y), df, y = 5:8) == 1:4 + 1:4
```

```{r}
f <- function(expr, data) eval(expr, data, rlang::caller_env())
f(quote(u + v), data.frame(u = 1:4, v = 1:4))
```


```{r}
fq <- function(expr, data) {
  eval(substitute(expr), data, rlang::caller_env())
}
fq(u + v, data.frame(u = 1:4, v = 1:4))
```


```{r, error=TRUE}
g <- function(expr) fq(expr, data.frame(u = 1:4, v = 1:4))
g(u + v)
```

```{r}
u <- v <- 5:8
g(u + v)
```

```{r}
g <- function(expr) {
  fq(substitute(expr), data.frame(u = 1:4, v = 1:4))
}
g(u + v)
```


```{r}
g <- function(expr) {
  fq(quote(expr), data.frame(u = 1:4, v = 1:4))
}
g(u + v)
```

```{r}
g <- function(expr) {
  f(substitute(expr), data.frame(u = 1:4, v = 1:4))
}
g(u + v)
```


```{r}
f <- function(expr, data) eval(expr, data, rlang::caller_env())
fq <- function(expr, data) f(substitute(expr), data)
fq(u + v, data.frame(u = 1:4, v = 1:4))
```


```{r}
g <- function(x, y, z) {
  w <- x + y + z
  f(quote(w + u + v), data.frame(u = 1:4, v = 1:4))
}
h <- function(x, y, z) {
  w <- x + y + z
  fq(w + u + v, data.frame(u = 1:4, v = 1:4))
}
```


```{r, error=TRUE}
g(1:4, 1:4, 1:4) == (1:4 + 1:4 + 1:4) + 1:4 + 1:4
h(1:4, 1:4, 1:4) == (1:4 + 1:4 + 1:4) + 1:4 + 1:4
```

```{r}
ff <- function(expr, data) {
  eval(expr[[2]], data, environment(expr))
}
ffq <- function(expr, data) {
  expr <- eval(substitute(~ expr))
  environment(expr) <- rlang::caller_env()
  ff(expr, data)
}
```


```{r}
g <- function(x, y, z) {
  w <- x + y + z
  ff(~ w + u + v, data.frame(u = 1:4, v = 1:4))
}
h <- function(x, y, z) {
  w <- x + y + z
  ffq(w + u + v, data.frame(u = 1:4, v = 1:4))
}
```

```{r}
g(1:4, 1:4, 1:4) == (1:4 + 1:4 + 1:4) + 1:4 + 1:4
h(1:4, 1:4, 1:4) == (1:4 + 1:4 + 1:4) + 1:4 + 1:4
```

